### ISSUE TITLE
calc_subbas: Snapping to flowlines can be problematic

### ISSUE THREAD

**Issue by TillF** [tpilz/lumpR#40]
Snapping to flow lines  (river) can result in outlet points, which are not intended (see pic: circle: original outlet point; arrow: snapped point; red cells: river from flowaccumualtion; orange: erroneously constructed basin; black line: expected watersshed). 
![snap2line](https://user-images.githubusercontent.com/11060560/41042583-53c869b6-69a2-11e8-983f-39317d6557d9.png)

**Comment by tpilz** [comment]
Actually I don't understand the point. Drainage points have to be located exactly in a river cell. That's why they are snapped. It only may happen that they are snapped to the wrong river. In such a case one have to correct the drainage points manually and re-run the R function (as written in the docs). Therefore, as I understand, the image looks exactly as one would expect?!
