### ISSUE TITLE
problem with installation in recent R

### ISSUE THREAD

**Issue by allayur** [tpilz/lumpR#56]
Sorry for very basic problem, but installing lump on a new windows machine I got a following error masage

Installing package into ‘C:/Users/allay/OneDrive/Документы/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'lumpR' ...
** using staged installation
Error in file(file, if (append) "a" else "w") : 
  (РєРѕРЅРІРµСЂС‚РёСЂРѕРІР°РЅРѕ РёР· РїСЂРµРґСѓРїСЂРµР¶РґРµРЅРёСЏ) РЅРµ РјРѕРіСѓ РѕС‚РєСЂС‹С‚СЊ С„Р°Р№Р» 'C:/Users/allay/OneDrive/Dnjslemr{/R/win-library/3.6/00LOCK-lumpR/00new/lumpR/DESCRIPTION': No such file or directory
ERROR: installing package DESCRIPTION failed for package 'lumpR'
* removing 'C:/Users/allay/OneDrive/Документы/R/win-library/3.6/lumpR'
Ошибка: Failed to install 'lumpR' from GitHub:
  (конвертировано из предупреждения) installation of package ‘C:/Users/allay/AppData/Local/Temp/Rtmpkt0Zhx/file2fec21573eae/lumpR_3.0.48.tar.gz’ had non-zero exit status

**Comment by TillF** [comment]
This message comes a result from a recent change in `install_github()`, which converts all warnings into errors. Warnings can be caused by 'newer package version available' or 'package was built under a newer version of R'. These warnings do not pose a problem, still the building process terminates.
To prevent this, please add
`Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)`
before executing `install_github()`
I added this hint to the installation steps in the readme.
